# -*- coding: utf-8 -*-
"""Copy of Numpy Practice 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FcNlpGWlXOwPnCc5GppEUxGI_LnwP9un

Welcome to the NumPy practice exercise! Please follow these instructions carefully to complete your assignment:

1. **Read Each Question Carefully**: Each question is designed to test different aspects of your NumPy skills. Make sure to understand what is being asked before you start coding.

2. **Write Your Code in the Provided Cells**: For each question, you will find a corresponding code cell where you should write your solution. Do not modify any other part of the notebook.

3. **Run Your Code**: After writing your code, run the cell to ensure that your solution works as expected. Check the output and make sure it meets the requirements specified in the question.

4. **Complete All Questions**: Make sure you answer all the questions provided. Each question has been included to assess a different skill or concept in NumPy.

5. **Download Your Notebook**: Once you have completed all questions and verified that your solutions are correct, download your notebook file (.ipynb). You can do this by selecting `File > Download > Download .ipynb` from the menu.

6. **Submit Your Work**: Upload the downloaded `.ipynb` file to the designated learning platform for submission.

7. **Check Your Submission**: Ensure that you have submitted the correct file and that it is not corrupted. If there are any issues with the file, you may need to resubmit.

Good luck, and happy coding!

Q1. Import Numpy as `np`
"""

# write your code here
import numpy as np

"""Q2. Create an array of 10 zeros."""

# write your code here
arr_zeros=np.zeros(10)
print(arr_zeros)

"""Q3. Create an array of 10 ones and the fifth value which is 0."""

# write your code here
arr_ones = np.ones(10)
arr_ones[4] = 0
print(arr_ones)

"""Q.4 Create an array of 10 fives"""

# write your code here
arr_fives = np.full(10,5)
print(arr_fives)

"""Q.5 Create an array of the integers from 10 to 50."""

# write your code here
arr_int = np.arange(10,51)
print(arr_int)

"""Q.6 Create an array of all even integers from 10 to 50."""

# write your code here
arr_even = np.arange(10,51,2)
print(arr_even)

"""Q.7 Create a 3x3 matrix with values ranging from 0 to 8.



"""

# write your code here
arr_matrix = np.arange(0,9).reshape(3,3)
print(arr_matrix)

"""Q.8 Create a 3x3 identity matrix."""

# write your code here
arr_identity = np.eye(3)
print(arr_identity)

"""Q.9 Use numpy to generate a random number between 0 to 1."""

# write your code here
arr_random = np.random.rand(1)
print(arr_random)

"""Q.10 Use numpy array to generate an array of 25 numbers."""

# write your code here
arr_random = np.random.rand(25)
print(arr_random)

"""Q.11 create the following matrix

```python
array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

  ```
"""

# write your code here
arr_matrix = np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(arr_matrix)

"""Q.12 Create an array of 20 linearly spaced points between 0 and 1."""

# write your code here
arr_linear = np.linspace(0,1,20)
print(arr_linear)

"""# End!"""